# Generated by Django 4.2.13 on 2024-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
