# Generated by Django 4.2.13 on 2024-05-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
