# Generated by Django 4.2.13 on 2024-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_delete_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('duration', models.TimeField()),
            ],
        ),
    ]
