# Generated by Django 4.2.13 on 2024-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='duration',
            field=models.CharField(max_length=5),
        ),
    ]
