# Generated by Django 4.2.13 on 2024-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_registration_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
